---
# Manage Repositories
- include: repos.yml
  when: scl_manage_repo

- include: wrappers.yml
  when: scl_wrappers | length > 0

- include: packages.yml
  when: scl_packages | length > 0

- include: gems.yml
  when: scl_ruby_gems | length > 0

- include: pips.yml
  when: scl_python_pips | length > 0
